### ISSUE TITLE
Размер шрифта субтитров

### ISSUE THREAD

**Issue by Bxaa** [BroFox86/ss2-rus#2]
Здравствуйте.
Спасибо за вашу работу!
У меня вопрос:
Возможно ли, как нибудь увеличить размер субтитров (шрифта) в игре? Может есть какое значение в конфигах или нужно конкретно заменить шрифт?
Движок, насколько я помню, такой же, как и у первого thief и там размер субтитров русификатора можно поменять. Уверен это возможно и для ss2...

**Comment by BroFox86** [comment]
Здравствуйте. 

Можно увеличить субтитры, но вместе со всем интерфейсом. Смотрите раздел "Увеличение интерфейса (HUD)": [Модификация System Shock 2](https://steamcommunity.com/sharedfiles/filedetails/?id=716333559)

**Comment by Bxaa** [comment]
Спасибо!

**Comment by Bxaa** [comment]
Спасибо!
